apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /nfsfileshare
    server: <put the IP@ of the NFS server>
  persistentVolumeReclaimPolicy: Retain
